output_site_var = {
    "Site Outdoor Air Drybulb Temperature", # Zone Average [C]
    "Site Outdoor Air Dewpoint Temperature",# Zone Average [C]
    "Site Outdoor Air Wetbulb Temperature", # Zone Average [C]
    "Site Outdoor Air Humidity Ratio", # Zone Average [kgWater/kgDryAir]
    "Site Outdoor Air Relative Humidity", # Zone Average [%]
    "Site Outdoor Air Barometric Pressure", # Zone Average [Pa]
    "Site Wind Speed", # Zone Average [m/s]
    "Site Wind Direction", # Zone Average [deg]
    "Site Sky Temperature", # Zone Average [C]
    "Site Horizontal Infrared Radiation Rate per Area", # Zone Average [W/m2]
    "Site Diffuse Solar Radiation Rate per Area", # Zone Average [W/m2]
    "Site Direct Solar Radiation Rate per Area", # Zone Average [W/m2]
    "Liquid Precipitation Depth", # Zone Sum [m] # TODO: Test this variable.
    "Site Precipitation Rate", # Zone Average [m/s]
    "Site Precipitation Depth", # Zone Sum [m]
    "Site Ground Reflected Solar Radiation Rate per Area", # Zone Average [W/m2]
    "Site Ground Temperature", # Zone Average [C]
    "Site Surface Ground Temperature", # Zone Average [C]
    "Site Deep Ground Temperature", # Zone Average [C]
    "Site Simple Factor Model Ground Temperature", # Zone Average [C]
    "Site Total Sky Cover", # Zone Average []
    "Site Opaque Sky Cover", # Zone Average []
    "Site Outdoor Air Enthalpy", # Zone Average [J/kg]
    "Site Outdoor Air Density", # Zone Average [kg/m3]
    "Site Solar Azimuth Angle", # Zone Average [deg]
    "Site Solar Altitude Angle", # Zone Average [deg]
    "Site Solar Hour Angle", # Zone Average [deg]
    "Site Rain Status", # Zone Average []
    "Site Snow on Ground Status", # Zone Average []
    "Site Exterior Horizontal Sky Illuminance", # Zone Average [lux]
    "Site Exterior Horizontal Beam Illuminance", # Zone Average [lux]
    "Site Exterior Beam Normal Illuminance", # Zone Average [lux]
    "Site Sky Diffuse Solar Radiation Luminous Efficacy", # Zone Average [lum/W]
    "Site Beam Solar Radiation Luminous Efficacy", # Zone Average [lum/W]
    "Site Daylighting Model Sky Clearness", # Zone Average []
    "Site Daylighting Model Sky Brightness", # Zone Average []
    "Site Daylight Saving Time Status", # Zone Average []
    "Site Day Type Index", # Zone Average []
    "Site Mains Water Temperature", # Zone Average [C]
}
output_tz_var = {
    "Zone Outdoor Air Drybulb Temperature", # Zone Average [C]
    "Zone Outdoor Air Wetbulb Temperature", # Zone Average [C]
    "Zone Outdoor Air Wind Speed", # Zone Average [m/s]
    "Zone Outdoor Air Wind Direction", # Zone Average [deg]
    "Enclosure Mean Radiant Temperature", # Zone Average [C]
    "Zone Total Internal Radiant Heating Energy", # Zone Sum [J]
    "Zone Total Internal Radiant Heating Rate", # Zone Average [W]
    "Zone Total Internal Visible Radiation Heating Energy", # Zone Sum [J]
    "Zone Total Internal Visible Radiation Heating Rate", # Zone Average [W]
    "Zone Total Internal Convective Heating Energy", # Zone Sum [J]
    "Zone Total Internal Convective Heating Rate", # Zone Average [W]
    "Zone Total Internal Latent Gain Energy", # Zone Sum [J]
    "Zone Total Internal Latent Gain Rate", # Zone Average [W]
    "Zone Total Internal Total Heating Energy", # Zone Sum [J]
    "Zone Total Internal Total Heating Rate", # Zone Average [W]
}

    Space Total Internal Radiant Heating Energy # Zone Sum [J]
    Space Total Internal Radiant Heating Rate # Zone Average [W]
    Space Total Internal Visible Radiation Heating Energy # Zone Sum [J]
    Space Total Internal Visible Radiation Heating Rate # Zone Average [W]
    Space Total Internal Convective Heating Energy # Zone Sum [J]
    Space Total Internal Convective Heating Rate # Zone Average [W]
    Space Total Internal Latent Gain Energy # Zone Sum [J]
    Space Total Internal Latent Gain Rate # Zone Average [W]
    Space Total Internal Total Heating Energy # Zone Sum [J]
    Space Total Internal Total Heating Rate # Zone Average [W]
    People Occupant Count # Zone Average []
    People Radiant Heating Energy # Zone Sum [J]
    People Radiant Heating Rate # Zone Average [W]
    People Convective Heating Energy # Zone Sum [J]
    People Convective Heating Rate # Zone Average [W]
    People Sensible Heating Energy # Zone Sum [J]
    People Sensible Heating Rate # Zone Average [W]
    People Latent Gain Energy # Zone Sum [J]
    People Latent Gain Rate # Zone Average [W]
    People Total Heating Energy # Zone Sum [J]
    People Total Heating Rate # Zone Average [W]
    People Air Temperature # Zone Average [C]
    People Air Relative Humidity # Zone Average [%]
    
    Zone People Occupant Count # Zone Average []
    Zone People Radiant Heating Energy # Zone Sum [J]
    Zone People Radiant Heating Rate # Zone Average [W]
    Zone People Convective Heating Energy # Zone Sum [J]
    Zone People Convective Heating Rate # Zone Average [W]
    Zone People Sensible Heating Energy # Zone Sum [J]
    Zone People Sensible Heating Rate # Zone Average [W]
    Zone People Latent Gain Energy # Zone Sum [J]
    Zone People Latent Gain Rate # Zone Average [W]
    Zone People Total Heating Energy # Zone Sum [J]
    Zone People Total Heating Rate # Zone Average [W]
    
    Space People Occupant Count # Zone Average []
    Space People Radiant Heating Energy # Zone Sum [J]
    Space People Radiant Heating Rate # Zone Average [W]
    Space People Convective Heating Energy # Zone Sum [J]
    Space People Convective Heating Rate # Zone Average [W]
    Space People Sensible Heating Energy # Zone Sum [J]
    Space People Sensible Heating Rate # Zone Average [W]
    Space People Latent Gain Energy # Zone Sum [J]
    Space People Latent Gain Rate # Zone Average [W]
    Space People Total Heating Energy # Zone Sum [J]
    Space People Total Heating Rate # Zone Average [W]
    
    Lights Electricity Rate # Zone Average [W]
    Lights Radiant Heating Energy # Zone Sum [J]
    Lights Radiant Heating Rate # Zone Average [W]
    Lights Visible Radiation Heating Energy # Zone Sum [J]
    Lights Visible Radiation Heating Rate # Zone Average [W]
    Lights Convective Heating Energy # Zone Sum [J]
    Lights Convective Heating Rate # Zone Average [W]
    Lights Return Air Heating Energy # Zone Sum [J]
    Lights Return Air Heating Rate # Zone Average [W]
    Lights Total Heating Energy # Zone Sum [J]
    Lights Total Heating Rate # Zone Average [W]
    Lights Electricity Energy # Zone Sum [J]
    
    Zone Lights Electricity Rate # Zone Average [W]
    Zone Lights Electricity Energy # Zone Sum [J]
    Zone Lights Radiant Heating Energy # Zone Sum [J]
    Zone Lights Radiant Heating Rate # Zone Average [W]
    Zone Lights Visible Radiation Heating Energy # Zone Sum [J]
    Zone Lights Visible Radiation Heating Rate # Zone Average [W]
    Zone Lights Convective Heating Energy # Zone Sum [J]
    Zone Lights Convective Heating Rate # Zone Average [W]
    Zone Lights Return Air Heating Energy # Zone Sum [J]
    Zone Lights Return Air Heating Rate # Zone Average [W]
    Zone Lights Total Heating Energy # Zone Sum [J]
    Zone Lights Total Heating Rate # Zone Average [W]
    
    Space Lights Electricity Rate # Zone Average [W]
    Space Lights Electricity Energy # Zone Sum [J]
    Space Lights Radiant Heating Energy # Zone Sum [J]
    Space Lights Radiant Heating Rate # Zone Average [W]
    Space Lights Visible Radiation Heating Energy # Zone Sum [J]
    Space Lights Visible Radiation Heating Rate # Zone Average [W]
    Space Lights Convective Heating Energy # Zone Sum [J]
    Space Lights Convective Heating Rate # Zone Average [W]
    Space Lights Return Air Heating Energy # Zone Sum [J]
    Space Lights Return Air Heating Rate # Zone Average [W]
    Space Lights Total Heating Energy # Zone Sum [J]
    Space Lights Total Heating Rate # Zone Average [W]
    
    Electric Equipment Electricity Rate # Zone Average [W]
    Electric Equipment Electricity Energy # Zone Sum [J]
    Electric Equipment Radiant Heating Energy # Zone Sum [J]
    Electric Equipment Radiant Heating Rate # Zone Average [W]
    Electric Equipment Convective Heating Energy # Zone Sum [J]
    Electric Equipment Convective Heating Rate # Zone Average [W]
    Electric Equipment Latent Gain Energy # Zone Sum [J]
    Electric Equipment Latent Gain Rate # Zone Average [W]
    Electric Equipment Lost Heat Energy # Zone Sum [J]
    Electric Equipment Lost Heat Rate # Zone Average [W]
    Electric Equipment Total Heating Energy # Zone Sum [J]
    Electric Equipment Total Heating Rate # Zone Average [W]
    
    Zone Electric Equipment Electricity Rate # Zone Average [W]
    Zone Electric Equipment Electricity Energy # Zone Sum [J]
    Zone Electric Equipment Radiant Heating Energy # Zone Sum [J]
    Zone Electric Equipment Radiant Heating Rate # Zone Average [W]
    Zone Electric Equipment Convective Heating Energy # Zone Sum [J]
    Zone Electric Equipment Convective Heating Rate # Zone Average [W]
    Zone Electric Equipment Latent Gain Energy # Zone Sum [J]
    Zone Electric Equipment Latent Gain Rate # Zone Average [W]
    Zone Electric Equipment Lost Heat Energy # Zone Sum [J]
    Zone Electric Equipment Lost Heat Rate # Zone Average [W]
    Zone Electric Equipment Total Heating Energy # Zone Sum [J]
    Zone Electric Equipment Total Heating Rate # Zone Average [W]
    
    Space Electric Equipment Electricity Rate # Zone Average [W]
    Space Electric Equipment Electricity Energy # Zone Sum [J]
    Space Electric Equipment Radiant Heating Energy # Zone Sum [J]
    Space Electric Equipment Radiant Heating Rate # Zone Average [W]
    Space Electric Equipment Convective Heating Energy # Zone Sum [J]
    Space Electric Equipment Convective Heating Rate # Zone Average [W]
    Space Electric Equipment Latent Gain Energy # Zone Sum [J]
    Space Electric Equipment Latent Gain Rate # Zone Average [W]
    Space Electric Equipment Lost Heat Energy # Zone Sum [J]
    Space Electric Equipment Lost Heat Rate # Zone Average [W]
    Space Electric Equipment Total Heating Energy # Zone Sum [J]
    Space Electric Equipment Total Heating Rate # Zone Average [W]
    
    Zone Windows Total Transmitted Solar Radiation Rate # Zone Average [W]
    Zone Exterior Windows Total Transmitted Beam Solar Radiation Rate # Zone Average [W]
    Zone Interior Windows Total Transmitted Beam Solar Radiation Rate # Zone Average [W]
    Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Rate # Zone Average [W]
    Zone Interior Windows Total Transmitted Diffuse Solar Radiation Rate # Zone Average [W]
    Zone Windows Total Transmitted Solar Radiation Energy # Zone Sum [J]
    Zone Exterior Windows Total Transmitted Beam Solar Radiation Energy # Zone Sum [J]
    Zone Interior Windows Total Transmitted Beam Solar Radiation Energy # Zone Sum [J]
    Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Energy # Zone Sum [J]
    Zone Interior Windows Total Transmitted Diffuse Solar Radiation Energy # Zone Sum [J]
    Zone Windows Total Heat Gain Rate # Zone Average [W]
    Zone Windows Total Heat Loss Rate # Zone Average [W]
    Zone Windows Total Heat Gain Energy # Zone Sum [J]
    Zone Windows Total Heat Loss Energy # Zone Sum [J]
    
    Surface Outside Normal Azimuth Angle # Zone Average [deg]
    Surface Outside Face Sunlit Area # Zone Average [m2]
    Surface Outside Face Sunlit Fraction # Zone Average []
    Surface Outside Face Incident Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Beam Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Sky Diffuse Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Ground Diffuse Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Beam Solar Incident Angle Cosine Value # Zone Average []
    Surface Outside Face Incident Sky Diffuse Ground Reflected Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Sky Diffuse Surface Reflected Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Beam To Beam Surface Reflected Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Beam To Diffuse Surface Reflected Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Outside Face Incident Beam To Diffuse Ground Reflected Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Anisotropic Sky Multiplier # Zone Average []
    Surface Window BSDF Beam Direction Number # Zone Average []
    Surface Window BSDF Beam Theta Angle # Zone Average [rad]
    Surface Window BSDF Beam Phi Angle # Zone Average [rad]
    Surface Window Total Glazing Layers Absorbed Solar Radiation Rate # Zone Average [W]
    Surface Window Total Glazing Layers Absorbed Shortwave Radiation Rate # Zone Average [W]
    Surface Window Front Face Temperature Layer 1 # Zone Average [C]
    Surface Window Back Face Temperature Layer 1 # Zone Average [C]
    Surface Window Transmitted Solar Radiation Rate # Zone Average [W]
    Surface Window Transmitted Beam Solar Radiation Rate # Zone Average [W]
    Surface Window Transmitted Beam To Beam Solar Radiation Rate # Zone Average [W]
    Surface Window Transmitted Beam To Diffuse Solar Radiation Rate # Zone Average [W]
    Surface Window Transmitted Diffuse Solar Radiation Rate # Zone Average [W]
    Surface Window Heat Gain Rate # Zone Average [W]
    Surface Window Heat Loss Rate # Zone Average [W]
    Surface Window Gap Convective Heat Transfer Rate # Zone Average [W]
    Surface Window Shading Device Absorbed Solar Radiation Rate # Zone Average [W]
    Surface Window Net Heat Transfer Rate # Zone Average [W]
    Surface Window Total Glazing Layers Absorbed Solar Radiation Energy # Zone Sum [J]
    Surface Window Transmitted Solar Radiation Energy # Zone Sum [J]
    Surface Window Transmitted Beam Solar Radiation Energy # Zone Sum [J]
    Surface Window Transmitted Beam To Beam Solar Radiation Energy # Zone Sum [J]
    Surface Window Transmitted Beam To Diffuse Solar Radiation Energy # Zone Sum [J]
    Surface Window Transmitted Diffuse Solar Radiation Energy # Zone Sum [J]
    Surface Window Heat Gain Energy # Zone Sum [J]
    Surface Window Heat Loss Energy # Zone Sum [J]
    Surface Window Gap Convective Heat Transfer Energy # Zone Sum [J]
    Surface Window Shading Device Absorbed Solar Radiation Energy # Zone Sum [J]
    Surface Window Net Heat Transfer Energy # Zone Sum [J]
    Surface Window System Solar Transmittance # Zone Average []
    Surface Window System Solar Reflectance # Zone Average []
    Surface Window System Solar Absorptance # Zone Average []
    Surface Window Inside Face Glazing Condensation Status # Zone Average []
    Surface Window Inside Face Frame Condensation Status # Zone Average []
    Surface Window Inside Face Divider Condensation Status # Zone Average []
    Surface Window Outside Reveal Reflected Beam Solar Radiation Rate # Zone Average [W]
    Surface Window Outside Reveal Reflected Beam Solar Radiation Energy # Zone Sum [J]
    Surface Window Solar Horizontal Profile Angle # Zone Average [deg]
    Surface Window Solar Vertical Profile Angle # Zone Average [deg]
    Surface Window Glazing Beam to Beam Solar Transmittance # Zone Average []
    Surface Window Glazing Beam to Diffuse Solar Transmittance # Zone Average []
    Surface Window Glazing Diffuse to Diffuse Solar Transmittance # Zone Average []
    Surface Window Model Solver Iteration Count # Zone Average []
    Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate # Zone Average [W]
    Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate per Area # Zone Average [W/m2]
    Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate # Zone Average [W]
    Surface Inside Face Initial Transmitted Diffuse Absorbed Solar Radiation Rate # Zone Average [W]
    Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate # Zone Average [W]
    Surface Inside Face Absorbed Shortwave Radiation Rate # Zone Average [W]
    Surface Inside Face Exterior Windows Incident Beam Solar Radiation Energy # Zone Sum [J]
    Surface Inside Face Interior Windows Incident Beam Solar Radiation Energy # Zone Sum [J]
    
    Debug Surface Solar Shading Model DifShdgRatioIsoSky # Zone Average []
    Debug Surface Solar Shading Model DifShdgRatioHoriz # Zone Average []
    Debug Surface Solar Shading Model WithShdgIsoSky # Zone Average []
    Debug Surface Solar Shading Model WoShdgIsoSky # Zone Average []
    
    Surface Inside Face Temperature # Zone Average [C]
    Surface Inside Face Interior Movable Insulation Temperature # Zone Average [C]
    Surface Outside Face Temperature # Zone Average [C]
    Surface Inside Face Adjacent Air Temperature # Zone Average [C]
    Surface Inside Face Convection Heat Transfer Coefficient # Zone Average [W/m2-K]
    Surface Inside Face Convection Heat Gain Rate # Zone Average [W]
    Surface Inside Face Convection Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face Convection Heat Gain Energy # Zone Sum [J]
    Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face Net Surface Thermal Radiation Heat Gain Energy # Zone Sum [J]
    Surface Inside Face Solar Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face Solar Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face Solar Radiation Heat Gain Energy # Zone Sum [J]
    Surface Inside Face Lights Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face Lights Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face Lights Radiation Heat Gain Energy # Zone Sum [J]
    Surface Inside Face Internal Gains Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face Internal Gains Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face Internal Gains Radiation Heat Gain Energy # Zone Sum [J]
    Surface Inside Face System Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face System Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Inside Face System Radiation Heat Gain Energy # Zone Sum [J]
    Surface Outside Face Outdoor Air Drybulb Temperature # Zone Average [C]
    Surface Outside Face Outdoor Air Wetbulb Temperature # Zone Average [C]
    Surface Outside Face Outdoor Air Wind Speed # Zone Average [m/s]
    Surface Outside Face Outdoor Air Wind Direction # Zone Average [deg]
    Surface Outside Face Convection Heat Gain Rate # Zone Average [W]
    Surface Outside Face Convection Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Outside Face Convection Heat Gain Energy # Zone Sum [J]
    Surface Outside Face Convection Heat Transfer Coefficient # Zone Average [W/m2-K]
    Surface Outside Face Net Thermal Radiation Heat Gain Rate # Zone Average [W]
    Surface Outside Face Net Thermal Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Outside Face Net Thermal Radiation Heat Gain Energy # Zone Sum [J]
    Surface Outside Face Thermal Radiation to Air Heat Transfer Coefficient # Zone Average [W/m2-K]
    Surface Outside Face Thermal Radiation to Sky Heat Transfer Coefficient # Zone Average [W/m2-K]
    Surface Outside Face Thermal Radiation to Ground Heat Transfer Coefficient # Zone Average [W/m2-K]
    Surface Outside Face Thermal Radiation to Air Heat Transfer Rate # Zone Average [W]
    Surface Outside Face Heat Emission to Air Rate # Zone Average [W]
    Surface Outside Face Solar Radiation Heat Gain Rate # Zone Average [W]
    Surface Outside Face Solar Radiation Heat Gain Rate per Area # Zone Average [W/m2]
    Surface Outside Face Solar Radiation Heat Gain Energy # Zone Sum [J]
    Surface Inside Face Conduction Heat Transfer Rate # Zone Average [W]
    Surface Inside Face Conduction Heat Gain Rate # Zone Average [W]
    Surface Inside Face Conduction Heat Loss Rate # Zone Average [W]
    Surface Inside Face Conduction Heat Transfer Rate per Area # Zone Average [W/m2]
    Surface Inside Face Conduction Heat Transfer Energy # Zone Sum [J]
    Surface Outside Face Conduction Heat Transfer Rate # Zone Average [W]
    Surface Outside Face Conduction Heat Gain Rate # Zone Average [W]
    Surface Outside Face Conduction Heat Loss Rate # Zone Average [W]
    Surface Outside Face Conduction Heat Transfer Rate per Area # Zone Average [W/m2]
    Surface Outside Face Conduction Heat Transfer Energy # Zone Sum [J]
    Surface Average Face Conduction Heat Transfer Rate # Zone Average [W]
    Surface Average Face Conduction Heat Gain Rate # Zone Average [W]
    Surface Average Face Conduction Heat Loss Rate # Zone Average [W]
    Surface Average Face Conduction Heat Transfer Rate per Area # Zone Average [W/m2]
    Surface Average Face Conduction Heat Transfer Energy # Zone Sum [J]
    Surface Heat Storage Rate # Zone Average [W]
    Surface Heat Storage Gain Rate # Zone Average [W]
    Surface Heat Storage Loss Rate # Zone Average [W]
    Surface Heat Storage Rate per Area # Zone Average [W/m2]
    Surface Heat Storage Energy # Zone Sum [J]
    Surface Inside Face Beam Solar Radiation Heat Gain Rate # Zone Average [W]
    Surface Inside Face Convection Classification Index # Zone Average []
    Surface Inside Face Convection Model Equation Index # Zone Average []
    Surface Inside Face Convection Reference Air Index # Zone Average []
    Surface Outside Face Convection Classification Index # Zone Average []
    Surface Outside Face Forced Convection Model Equation Index # Zone Average []
    Surface Outside Face Natural Convection Model Equation Index # Zone Average []
    Surface Inside Face Heat Source Gain Rate per Area # Zone Average [W/m2]
    Surface Outside Face Heat Source Gain Rate per Area # Zone Average [W/m2]
    Surface Shading Device Is On Time Fraction # Zone Average []
    Surface Storm Window On Off Status # Zone Average []
    Surface Window Blind Slat Angle # Zone Average [deg]
    
    Site Total Surface Heat Emission to Air # Zone Sum [J]
    
    Zone Mean Air Temperature # Zone Average [C]
    Zone Operative Temperature # Zone Average [C]
    Zone Mean Air Dewpoint Temperature # Zone Average [C]
    Zone Mean Air Humidity Ratio # Zone Average [kgWater/kgDryAir]
    Zone Air Heat Balance Internal Convective Heat Gain Rate,HVAC Average [W]
    Zone Air Heat Balance Surface Convection Rate,HVAC Average [W]
    Zone Air Heat Balance Interzone Air Transfer Rate,HVAC Average [W]
    Zone Air Heat Balance Outdoor Air Transfer Rate,HVAC Average [W]
    Zone Air Heat Balance System Air Transfer Rate,HVAC Average [W]
    Zone Air Heat Balance System Convective Heat Gain Rate,HVAC Average [W]
    Zone Air Heat Balance Air Energy Storage Rate,HVAC Average [W]
    Zone Exfiltration Heat Transfer Rate,HVAC Average [W]
    Zone Exfiltration Sensible Heat Transfer Rate,HVAC Average [W]
    Zone Exfiltration Latent Heat Transfer Rate,HVAC Average [W]
    Zone Exhaust Air Heat Transfer Rate,HVAC Average [W]
    Zone Exhaust Air Sensible Heat Transfer Rate,HVAC Average [W]
    Zone Exhaust Air Latent Heat Transfer Rate,HVAC Average [W]
    
    Site Total Zone Exfiltration Heat Loss,HVAC Sum [J]
    Site Total Zone Exhaust Air Heat Loss,HVAC Sum [J]
    
    AFN Node Temperature,HVAC Average [C]
    AFN Node Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    AFN Node Total Pressure,HVAC Average [Pa]
    AFN Node Wind Pressure,HVAC Average [Pa]
    AFN Linkage Node 1 to Node 2 Mass Flow Rate,HVAC Average [kg/s]
    AFN Linkage Node 2 to Node 1 Mass Flow Rate,HVAC Average [kg/s]
    AFN Linkage Node 1 to Node 2 Volume Flow Rate,HVAC Average [m3/s]
    AFN Linkage Node 2 to Node 1 Volume Flow Rate,HVAC Average [m3/s]
    AFN Linkage Node 1 to Node 2 Pressure Difference,HVAC Average [Pa]
    AFN Surface Venting Window or Door Opening Factor,HVAC Average []
    AFN Surface Venting Window or Door Opening Modulation Multiplier,HVAC Average []
    AFN Surface Venting Inside Setpoint Temperature,HVAC Average [C]
    AFN Surface Venting Availability Status,HVAC Average []
    AFN Zone Infiltration Sensible Heat Gain Rate,HVAC Average [W]
    AFN Zone Infiltration Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Ventilation Sensible Heat Gain Rate,HVAC Average [W]
    AFN Zone Ventilation Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Mixing Sensible Heat Gain Rate,HVAC Average [W]
    AFN Zone Mixing Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Infiltration Sensible Heat Loss Rate,HVAC Average [W]
    AFN Zone Infiltration Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Zone Ventilation Sensible Heat Loss Rate,HVAC Average [W]
    AFN Zone Ventilation Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Zone Mixing Sensible Heat Loss Rate,HVAC Average [W]
    AFN Zone Mixing Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Zone Infiltration Latent Heat Gain Rate,HVAC Average [W]
    AFN Zone Infiltration Latent Heat Gain Energy,HVAC Sum [J]
    AFN Zone Infiltration Latent Heat Loss Rate,HVAC Average [W]
    AFN Zone Infiltration Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Ventilation Latent Heat Gain Rate,HVAC Average [W]
    AFN Zone Ventilation Latent Heat Gain Energy,HVAC Sum [J]
    AFN Zone Ventilation Latent Heat Loss Rate,HVAC Average [W]
    AFN Zone Ventilation Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Mixing Latent Heat Gain Rate,HVAC Average [W]
    AFN Zone Mixing Latent Heat Gain Energy,HVAC Sum [J]
    AFN Zone Mixing Latent Heat Loss Rate,HVAC Average [W]
    AFN Zone Mixing Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Duct Leaked Air Sensible Heat Gain Rate,HVAC Average [W]
    AFN Zone Duct Leaked Air Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Duct Leaked Air Sensible Heat Loss Rate,HVAC Average [W]
    AFN Zone Duct Leaked Air Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Zone Duct Leaked Air Latent Heat Gain Rate,HVAC Average [W]
    AFN Zone Duct Leaked Air Latent Heat Gain Energy,HVAC Sum [J]
    AFN Zone Duct Leaked Air Latent Heat Loss Rate,HVAC Average [W]
    AFN Zone Duct Leaked Air Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Duct Conduction Sensible Heat Gain Rate,HVAC Average [W]
    AFN Zone Duct Conduction Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Duct Conduction Sensible Heat Loss Rate,HVAC Average [W]
    AFN Zone Duct Conduction Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Zone Duct Diffusion Latent Heat Gain Rate,HVAC Average [W]
    AFN Zone Duct Diffusion Latent Heat Gain Energy,HVAC Sum [J]
    AFN Zone Duct Diffusion Latent Heat Loss Rate,HVAC Average [W]
    AFN Zone Duct Diffusion Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Duct Radiation Heat Gain Rate,HVAC Average [W]
    AFN Zone Duct Radiation Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Zone Duct Radiation Heat Loss Rate,HVAC Average [W]
    AFN Zone Duct Radiation Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Distribution Sensible Heat Gain Rate,HVAC Average [W]
    AFN Distribution Sensible Heat Gain Energy,HVAC Sum [J]
    AFN Distribution Sensible Heat Loss Rate,HVAC Average [W]
    AFN Distribution Sensible Heat Loss Energy,HVAC Sum [J]
    AFN Distribution Latent Heat Gain Rate,HVAC Average [W]
    AFN Distribution Latent Heat Gain Energy,HVAC Sum [J]
    AFN Distribution Latent Heat Loss Rate,HVAC Average [W]
    AFN Distribution Latent Heat Loss Energy,HVAC Sum [J]
    AFN Zone Infiltration Volume,HVAC Sum [m3]
    AFN Zone Infiltration Mass,HVAC Sum [kg]
    AFN Zone Infiltration Air Change Rate,HVAC Average [ach]
    AFN Zone Ventilation Volume,HVAC Sum [m3]
    AFN Zone Ventilation Mass,HVAC Sum [kg]
    AFN Zone Ventilation Air Change Rate,HVAC Average [ach]
    AFN Zone Mixing Volume,HVAC Sum [m3]
    AFN Zone Mixing Mass,HVAC Sum [kg]
    AFN Zone Exfiltration Heat Transfer Rate,HVAC Average [W]
    AFN Zone Exfiltration Sensible Heat Transfer Rate,HVAC Average [W]
    AFN Zone Exfiltration Latent Heat Transfer Rate,HVAC Average [W]
    
    Zone Air Temperature,HVAC Average [C]
    Zone Air Humidity Ratio,HVAC Average []
    Zone Air Relative Humidity,HVAC Average [%]
    Zone Mean Radiant Temperature # Zone Average [C]
    Zone Air System Sensible Heating Energy,HVAC Sum [J]
    Zone Air System Sensible Cooling Energy,HVAC Sum [J]
    Zone Air System Sensible Heating Rate,HVAC Average [W]
    Zone Air System Sensible Cooling Rate,HVAC Average [W]
    Zone Predicted Sensible Load to Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone Predicted Sensible Load to Heating Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone Predicted Sensible Load to Cooling Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone System Predicted Sensible Load to Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone System Predicted Sensible Load to Heating Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone System Predicted Sensible Load to Cooling Setpoint Heat Transfer Rate,HVAC Average [W]
    Zone Predicted Moisture Load Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone Predicted Moisture Load to Humidifying Setpoint Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone Predicted Moisture Load to Dehumidifying Setpoint Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone System Predicted Moisture Load Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone System Predicted Moisture Load to Humidifying Setpoint Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone System Predicted Moisture Load to Dehumidifying Setpoint Moisture Transfer Rate,HVAC Average [kgWater/s]
    Zone Thermostat Air Temperature,HVAC Average [C]
    Zone Thermostat Control Type # Zone Average []
    Zone Thermostat Heating Setpoint Temperature,HVAC Average [C]
    Zone Thermostat Cooling Setpoint Temperature,HVAC Average [C]
    Zone Adaptive Comfort Operative Temperature Set Point # Zone Average [C]
    Zone Predicted Sensible Load Room Air Correction Factor,HVAC Average []
    
    HVAC System Solver Iteration Count,HVAC Sum []
    
    Air System Solver Iteration Count,HVAC Sum []
    Air System Relief Air Total Heat Loss Energy,HVAC Sum [J]
    
    HVAC System Total Heat Rejection Energy,HVAC Sum [J]
    
    Zone Ideal Loads Supply Air Sensible Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Latent Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Total Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Sensible Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Latent Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Total Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Sensible Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Latent Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Total Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Sensible Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Latent Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Zone Total Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Sensible Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Latent Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Total Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Sensible Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Latent Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Outdoor Air Total Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Sensible Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Latent Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Total Heating Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Sensible Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Latent Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Heat Recovery Total Cooling Energy,HVAC Sum [J]
    Zone Ideal Loads Supply Air Sensible Heating Rate,HVAC Average [W]
    Zone Ideal Loads Supply Air Latent Heating Rate,HVAC Average [W]
    Zone Ideal Loads Supply Air Total Heating Rate,HVAC Average [W]
    Zone Ideal Loads Supply Air Sensible Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Supply Air Latent Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Supply Air Total Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Zone Sensible Heating Rate,HVAC Average [W]
    Zone Ideal Loads Zone Latent Heating Rate,HVAC Average [W]
    Zone Ideal Loads Zone Total Heating Rate,HVAC Average [W]
    Zone Ideal Loads Zone Sensible Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Zone Latent Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Zone Total Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Sensible Heating Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Latent Heating Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Total Heating Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Sensible Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Latent Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Outdoor Air Total Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Sensible Heating Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Latent Heating Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Total Heating Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Sensible Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Latent Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Heat Recovery Total Cooling Rate,HVAC Average [W]
    Zone Ideal Loads Economizer Active Time,HVAC Sum [hr]
    Zone Ideal Loads Heat Recovery Active Time,HVAC Sum [hr]
    Zone Ideal Loads Hybrid Ventilation Available Status,HVAC Average []
    Zone Ideal Loads Outdoor Air Mass Flow Rate,HVAC Average [kg/s]
    Zone Ideal Loads Outdoor Air Standard Density Volume Flow Rate,HVAC Average [m3/s]
    Zone Ideal Loads Supply Air Mass Flow Rate,HVAC Average [kg/s]
    Zone Ideal Loads Supply Air Standard Density Volume Flow Rate,HVAC Average [m3/s]
    Zone Ideal Loads Supply Air Temperature,HVAC Average [C]
    Zone Ideal Loads Supply Air Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    Zone Ideal Loads Mixed Air Temperature,HVAC Average [C]
    Zone Ideal Loads Mixed Air Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    
    Air System Simulation Maximum Iteration Count,HVAC Sum []
    Air System Simulation Iteration Count,HVAC Sum []
    Air System Component Model Simulation Calls,HVAC Sum []
    
    Facility Total Purchased Electricity Rate,HVAC Average [W]
    Facility Total Purchased Electricity Energy,HVAC Sum [J]
    Facility Total Surplus Electricity Rate,HVAC Average [W]
    Facility Total Surplus Electricity Energy,HVAC Sum [J]
    Facility Net Purchased Electricity Rate,HVAC Average [W]
    Facility Net Purchased Electricity Energy,HVAC Sum [J]
    Facility Total Building Electricity Demand Rate,HVAC Average [W]
    Facility Total HVAC Electricity Demand Rate,HVAC Average [W]
    Facility Total Electricity Demand Rate,HVAC Average [W]
    Facility Total Produced Electricity Rate,HVAC Average [W]
    Facility Total Produced Electricity Energy,HVAC Sum [J]
    
    Zone Oscillating Temperatures Time,HVAC Sum [hr]
    Zone Oscillating Temperatures During Occupancy Time,HVAC Sum [hr]
    Zone Oscillating Temperatures in Deadband Time,HVAC Sum [hr]
    
    Facility Any Zone Oscillating Temperatures Time,HVAC Sum [hr]
    Facility Any Zone Oscillating Temperatures During Occupancy Time,HVAC Sum [hr]
    Facility Any Zone Oscillating Temperatures in Deadband Time,HVAC Sum [hr]
    
    Zone Thermal Comfort Fanger Model PMV # Zone Average []
    Zone Thermal Comfort Fanger Model PPD # Zone Average [%]
    Zone Thermal Comfort Clothing Surface Temperature # Zone Average [C]
    Zone Thermal Comfort Mean Radiant Temperature # Zone Average [C]
    Zone Thermal Comfort Operative Temperature # Zone Average [C]
    Zone Thermal Comfort Clothing Value # Zone Average [clo]
    Zone Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time # Zone Sum [hr]
    Zone Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time # Zone Sum [hr]
    Zone Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time # Zone Sum [hr]
    Facility Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time # Zone Sum [hr]
    Facility Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time # Zone Sum [hr]
    Facility Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time # Zone Sum [hr]
    
    Zone Heating Setpoint Not Met Time # Zone Sum [hr]
    Zone Heating Setpoint Not Met While Occupied Time # Zone Sum [hr]
    Zone Cooling Setpoint Not Met Time # Zone Sum [hr]
    Zone Cooling Setpoint Not Met While Occupied Time # Zone Sum [hr]
    
    Facility Heating Setpoint Not Met Time # Zone Sum [hr]
    Facility Cooling Setpoint Not Met Time # Zone Sum [hr]
    Facility Heating Setpoint Not Met While Occupied Time # Zone Sum [hr]
    Facility Cooling Setpoint Not Met While Occupied Time # Zone Sum [hr]
    
    Zone Heat Index # Zone Average [C]
    Zone Humidity Index # Zone Average []
    
    Schedule Value # Zone Average []
    
    Performance Curve Input Variable 1 Value,HVAC Average []
    Performance Curve Output Value,HVAC Average []
    
    System Node Temperature,HVAC Average [C]
    System Node Mass Flow Rate,HVAC Average [kg/s]
    System Node Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    System Node Setpoint Temperature,HVAC Average [C]
    System Node Setpoint High Temperature,HVAC Average [C]
    System Node Setpoint Low Temperature,HVAC Average [C]
    System Node Setpoint Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    System Node Setpoint Minimum Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    System Node Setpoint Maximum Humidity Ratio,HVAC Average [kgWater/kgDryAir]
    System Node Relative Humidity,HVAC Average [%]
    System Node Pressure,HVAC Average [Pa]
    System Node Standard Density Volume Flow Rate,HVAC Average [m3/s]
    System Node Current Density Volume Flow Rate,HVAC Average [m3/s]
    System Node Current Density,HVAC Average [kg/m3]
    System Node Specific Heat,HVAC Average [J/kg-K]
    System Node Enthalpy,HVAC Average [J/kg]
    System Node Wetbulb Temperature,HVAC Average [C]
    System Node Dewpoint Temperature,HVAC Average [C]
    System Node Wind Speed,HVAC Average [m/s]
    System Node Wind Direction,HVAC Average [deg]
    System Node Quality,HVAC Average []
    System Node Height,HVAC Average [m]
    
    Environmental Impact Total N2O Emissions Carbon Equivalent Mass,HVAC Sum [kg]
    Environmental Impact Total CH4 Emissions Carbon Equivalent Mass,HVAC Sum [kg]
    Environmental Impact Total CO2 Emissions Carbon Equivalent Mass,HVAC Sum [kg]
    
    Zone Mechanical Ventilation No Load Heat Removal Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Cooling Load Increase Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Cooling Load Increase Due to Overheating Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Cooling Load Decrease Energy,HVAC Sum [J]
    Zone Mechanical Ventilation No Load Heat Addition Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Heating Load Increase Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Heating Load Increase Due to Overcooling Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Heating Load Decrease Energy,HVAC Sum [J]
    Zone Mechanical Ventilation Mass Flow Rate,HVAC Average [kg/s]
    Zone Mechanical Ventilation Mass,HVAC Sum [kg]
    Zone Mechanical Ventilation Standard Density Volume Flow Rate,HVAC Average [m3/s]
    Zone Mechanical Ventilation Standard Density Volume,HVAC Sum [m3]
    Zone Mechanical Ventilation Current Density Volume Flow Rate,HVAC Average [m3/s]
    Zone Mechanical Ventilation Current Density Volume,HVAC Sum [m3]
    Zone Mechanical Ventilation Air Changes per Hour,HVAC Average [ach]
    Zone Target Voz Ventilation Flow Rate,HVAC Average [m3/s]
    Zone Ventilation Below Target Voz Time,HVAC Sum [hr]
    Zone Ventilation At Target Voz Time,HVAC Sum [hr]
    Zone Ventilation Above Target Voz Time,HVAC Sum [hr]
    Zone Ventilation When Unoccupied Time,HVAC Sum [hr]
    
    Facility Any Zone Ventilation Below Target Voz Time,HVAC Sum [hr]
    Facility All Zones Ventilation At Target Voz Time,HVAC Sum [hr]
    Facility Any Zone Ventilation Above Target Voz Time,HVAC Sum [hr]
    Facility Any Zone Ventilation When Unoccupied Time,HVAC Sum [hr]

