[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eprllib"
version = "0.0.1"
authors = [
  { name="Germán Rodolfo Henderson"},
]
description = "Building control trought DRL."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/hermmanhender/natural_ventilation_EP_RLlib"
"Bug Tracker" = "https://github.com/hermmanhender/natural_ventilation_EP_RLlib/issues"
