[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "eprllib"
version = "0.0.3"
authors = [
  { name="Germán Rodolfo Henderson"},
]
description = "Building control trought DRL."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "tensorflow ==2.15.0",
    "torch ==2.1.2",
    "ray[all] ==9.2.3",
    "bayesian-optimization ==1.4.3",
    "gymnasium ==0.28.1"
]

[project.urls]
"Homepage" = "https://github.com/hermmanhender/natural_ventilation_EP_RLlib"
"Bug Tracker" = "https://github.com/hermmanhender/natural_ventilation_EP_RLlib/issues"
