# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: eprllib

on:
  release:
    types: [published]

# Se ha eliminado FORCE_JAVASCRIPT_ACTIONS_TO_NODE24 para evitar la advertencia de forzado.

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    # Actualizado a la versión v4
    - uses: actions/checkout@v4
    
    # Actualizado a la versión v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install twine
        pip install ray[all] >=2.20.0
        pip install gymnasium >=0.28.1
        pip install torch >=2.5.1
        pip install shap >=0.46.0
        pip install matplotlib >=3.8.0
        
    - name: Build package
      run: python -m build
      
    - name: eprllib
      # Actualizado a release/v1 que es la práctica recomendada actual
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}